export const COLLECTIONS = {
  users: 'users',
  demoRequests: 'demoRequests',
  leads: 'leads',
  proposals: 'proposals',
  projects: 'projects',
  payments: 'payments',
  businesses: 'businesses',
  products: 'products',
  orders: 'orders',
  assets: 'assets',
  tickets: 'tickets',
  affiliates: 'affiliates',
  referrals: 'referrals',
  notifications: 'notifications',
  prospects: 'prospects',
  prospectHistory: 'prospectHistory',
  commissions: 'commissions',
  reminders: 'reminders',
  auditLogs: 'auditLogs',
  projectTimeline: 'projectTimeline',
  clientTickets: 'clientTickets',
  demoWizardSessions: 'demoWizardSessions',
} as const
